### ISSUE TITLE
create cluster failed

### ISSUE THREAD

**Issue by cleverhu** [kubean-io/kubean#454]
**Describe the version**
version about:
1. kubean
v0.4.2-rc3-23-gfa9d3050
v0.3.4
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
create cluster failed and the log is not detailed, I have add the unsafe_show_logs and -vvv to create cluster operation.

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**
create cluster successfully
**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

```
<10.6.106.163> (0, b'', b'')
ok: [controller-node-2] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "autoremove": false,
            "bugfix": false,
            "cacheonly": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_dir": null,
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 30,
            "name": [
                "iputils"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "present",
            "update_cache": false,
            "update_only": false,
            "use_backend": "auto",
            "validate_certs": true
        }
    },
    "msg": "",
    "rc": 0,
    "results": [
        "iputils-20160308-10.el7.x86_64 providing iputils is already installed"
    ]
}
<10.6.106.153> (0, b'\r\n{"msg": "", "invocation": {"module_args": {"lock_timeout": 30, "update_cache": false, "conf_file": null, "exclude": [], "allow_downgrade": false, "disable_gpg_check": false, "disable_excludes": null, "use_backend": "auto", "state": "present", "disablerepo": [], "skip_broken": false, "releasever": null, "cacheonly": false, "autoremove": false, "download_dir": null, "enable_plugin": [], "installroot": "/", "install_weak_deps": true, "name": ["iputils"], "download_only": false, "bugfix": false, "list": null, "install_repoquery": true, "update_only": false, "disable_plugin": [], "enablerepo": [], "security": false, "validate_certs": true}}, "changed": false, "results": ["iputils-20160308-10.el7.x86_64 providing iputils is already installed"], "rc": 0}\r\n', b'Shared connection to 10.6.106.153 closed.\r\n')
<10.6.106.153> ESTABLISH SSH CONNECTION FOR USER: root
<10.6.106.153> SSH: EXEC sshpass -d14 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/509b024db1"' 10.6.106.153 '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1672819883.9781415-1358-158887772964494/ > /dev/null 2>&1 && sleep 0'"'"''
<10.6.106.153> ESTABLISH SSH CONNECTION FOR USER: root
<10.6.106.153> SSH: EXEC sshpass -d14 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/509b024db1"' 10.6.106.153 '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1672819883.9781415-1358-158887772964494/ > /dev/null 2>&1 && sleep 0'"'"''
<10.6.106.153> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/local/lib/python3.8/dist-packages/ansible/executor/task_executor.py", line 600, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/package.py", line 94, in run
    self._remove_tmp_path(self._connection._shell.tmpdir)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/__init__.py", line 454, in _remove_tmp_path
    tmp_rm_res = self._low_level_execute_command(cmd, sudoable=False)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/__init__.py", line 1253, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/connection/ssh.py", line 1309, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/connection/ssh.py", line 474, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/connection/ssh.py", line 1167, in _run
    return self._bare_run(cmd, in_data, sudoable=sudoable, checkrc=checkrc)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/connection/ssh.py", line 924, in _bare_run
    os.write(self.sshpass_pipe[1], to_bytes(conn_password) + b'\n')
BrokenPipeError: [Errno 32] Broken pipe
fatal: [controller-node-3]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
controller-node-1          : ok=33   changed=0    unreachable=0    failed=0    skipped=51   rescued=0    ignored=0
controller-node-2          : ok=30   changed=0    unreachable=0    failed=0    skipped=39   rescued=0    ignored=0
controller-node-3          : ok=29   changed=0    unreachable=0    failed=1    skipped=39   rescued=0    ignored=0
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Wednesday 04 January 2023  08:11:26 +0000 (0:00:05.188)       0:03:16.907 *****
===============================================================================
bootstrap-os : Install libselinux python package ----------------------- 14.95s
/kubespray/roles/bootstrap-os/tasks/bootstrap-centos.yml:112 ------------------
bootstrap-os : Gather host facts to get ansible_distribution_version ansible_distribution_major_version -- 14.81s
/kubespray/roles/bootstrap-os/tasks/bootstrap-centos.yml:2 --------------------
download : download | Download files / images -------------------------- 10.56s
/kubespray/roles/download/tasks/main.yml:19 -----------------------------------
download : download | Download files / images -------------------------- 10.36s
/kubespray/roles/download/tasks/main.yml:19 -----------------------------------
adduser : User | Create User -------------------------------------------- 8.17s
/kubespray/roles/adduser/tasks/main.yml:7 -------------------------------------
Gather necessary facts (network) ---------------------------------------- 7.79s
/kubespray/facts.yml:16 -------------------------------------------------------
kubernetes/preinstall : Remove swapfile from /etc/fstab ----------------- 6.76s
/kubespray/roles/kubernetes/preinstall/tasks/0010-swapoff.yml:2 ---------------
kubernetes/preinstall : check swap -------------------------------------- 6.73s
/kubespray/roles/kubernetes/preinstall/tasks/0010-swapoff.yml:12 --------------
bootstrap-os : Assign inventory name to unconfigured hostnames (non-CoreOS, non-Flatcar, Suse and ClearLinux, non-Fedora) --- 6.53s
/kubespray/roles/bootstrap-os/tasks/main.yml:55 -------------------------------
adduser : User | Create User Group -------------------------------------- 6.34s
/kubespray/roles/adduser/tasks/main.yml:2 -------------------------------------
Gather necessary facts (hardware) --------------------------------------- 6.15s
/kubespray/facts.yml:24 -------------------------------------------------------
bootstrap-os : Create remote_tmp for it is used by another module ------- 5.47s
/kubespray/roles/bootstrap-os/tasks/main.yml:42 -------------------------------
kubernetes/preinstall : Ensure ping package ----------------------------- 5.19s
/kubespray/roles/kubernetes/preinstall/tasks/0020-verify-settings.yml:103 -----
bootstrap-os : Add proxy to yum.conf or dnf.conf if http_proxy is defined --- 5.02s
/kubespray/roles/bootstrap-os/tasks/bootstrap-centos.yml:7 --------------------
bootstrap-os : Check presence of fastestmirror.conf --------------------- 4.95s
/kubespray/roles/bootstrap-os/tasks/bootstrap-centos.yml:90 -------------------
bootstrap-os : Disable fastestmirror plugin if requested ---------------- 4.10s
/kubespray/roles/bootstrap-os/tasks/bootstrap-centos.yml:99 -------------------
Gather minimal facts ---------------------------------------------------- 3.85s
/kubespray/facts.yml:7 --------------------------------------------------------
bootstrap-os : Ensure bash_completion.d folder exists ------------------- 3.68s
/kubespray/roles/bootstrap-os/tasks/main.yml:102 ------------------------------
bootstrap-os : Gather host facts to get ansible_os_family --------------- 3.44s
/kubespray/roles/bootstrap-os/tasks/main.yml:50 -------------------------------
bootstrap-os : Enable Oracle Linux repo --------------------------------- 3.10s
/kubespray/roles/bootstrap-os/tasks/bootstrap-centos.yml:55 -------------------
```
**Additional context**

**Comment by ErikJiang** [comment]
Problems that cannot be reproduced
